version: "3.9"

services:
  backend:
    container_name: poapcentral-backend
    build: backend
    pull_policy: build
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/backend/api
        target: /backend/api
    ports:
      - 127.0.0.1:5196:5196
    networks:
      - poapcentral
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "curl",
    #       "-A",
    #       "healthcheck",
    #       "-f",
    #       "http://localhost:5196/health"
    #     ]
    #   interval: 1s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 10s
  frontend:
    container_name: poapcentral-frontend
    build: frontend
    pull_policy: build
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/frontend/public
        target: /frontend/public
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/frontend/src
        target: /frontend/src
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/frontend/astro.config.mjs
        target: /frontend/astro.config.mjs
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/frontend/bun.lockb
        target: /frontend/bun.lockb
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/frontend/package.json
        target: /frontend/package.json
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/frontend/tsconfig.json
        target: /frontend/tsconfig.json
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/frontend/.env
        target: /frontend/.env
        bind:
          create_host_path: true
    ports:
      - 127.0.0.1:4321:4321
    networks:
      - poapcentral
    # healthcheck:
    #   test:
    #     [
    #       "CMD",
    #       "curl",
    #       "-A",
    #       "healthcheck",
    #       "-f",
    #       "http://localhost:4321/health"
    #     ]
    #   interval: 1s
    #   timeout: 5s
    #   retries: 3
    #   start_period: 10s
  db:
    container_name: poapcentral-db
    image: postgres:16.1
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ${LOCAL_WORKSPACE_FOLDER:-.}/vol/db
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=poapcentral
      - POSTGRES_DB=postgres
      - TZ=UTC
      - PGTZ=UTC
    healthcheck:
      test: [
        "CMD-SHELL",
        "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-$${POSTGRES_USER:-postgres}}"
      ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - poapcentral
#   db-admin:
#     container_name: poapcentral-db-admin
#     image: dpage/pgadmin4
#     restart: unless-stopped
#     ports:
#       - 8080:8080
networks:
  poapcentral:
    name: poapcentral
    driver: bridge
